#!/bin/bash

if ! command -v "npx" &> /dev/null;then
    echo "ERROR: npx could not be found"
    exit 1
fi

JSLastModified=$(date -r js/index.js +%s)
minifiedJSLastModified=$(date -r js/index.min.js +%s)

# Staged files
changed_files=($(git diff --name-only --cached))

for file in "${changed_files[@]}"; do
  if [[ $file == js/index.js ]];then
    JSChanged=1
  elif [[ $file == js/index.min.js ]];then
    minifiedJSChanged=1
  fi
done

if [[ $JSChanged && ($JSLastModified -gt $minifiedJSLastModified || ! $minifiedJSChanged) ]];then
  if [[ $JSLastModified -gt $minifiedJSLastModified ]]; then
    echo "ERROR: staged minified version is not up to date"
    echo "INFO: Auto minifying"
    npx minify js/index.js > js/index.min.js
  fi

  echo "ERROR: updated minfied file not stage for commit"
  echo "INFO: Please add js/index.min.js and recommit"
  exit 1
elif [[ $JSChanged ]];then 
  echo "INFO: minified js has been modified after original js file and is believed to be up to date"
fi
